### PR TITLE
Include description, features and contributors

### PR DESCRIPTION
**Pull request by Inge505**
Which parts of Arne's code should we include/exclude?

### CODE REVIEW

**Review by JulianPienaar — COMMENTED** [review]
Good changes to the README

**Comment by JanSpies82** [comment]
Maybe for now the 3 yarn commands for running the app while the app is still under development? Then after that instructions on how to access the app/getting it running once it has been deployed?

**Review by JanSpies82 — APPROVED** [review]
Looks good :-)

**Review by chrislom12 — APPROVED** [review]
Good initial update to README

**Pull request merged**
